### ISSUE TITLE
How Tech Can Help - Problem Statement 2

### ISSUE THREAD

**Issue by TheITArchiTech** [Call-for-Code/Embrace-Judicial-Reform#6]
Update the "How tech can help" subsection of problem statement 2 to the following:

How tech can help

Technology can be used to measure the frequency of police behavioral infractions, such as, the unnecessary use of force or other aggressive tactics, and other incidents, which disproportionately target the black community. This will allow for the identification of any inherent biases that may have been associated with an incident. This data can subsequently be used to identify malicious police practices and help to improve relationships between the police and the communities which they swear to protect and serve.

**Comment by daveshack-ibm** [comment]
Seems reasonable, and we can always update it again as needed.  To give myself some practice on editing I'll incorporate this into a PR that also updates the readme.md file to 80 character lines as suggested by a colleague in another embrace repo.

**Comment by TheITArchiTech** [comment]
Very agile in nature @daveshack-ibm !
